const STOP_WORDS = new Set([
  "about",
  "after",
  "again",
  "also",
  "because",
  "before",
  "being",
  "could",
  "every",
  "from",
  "have",
  "into",
  "just",
  "like",
  "more",
  "other",
  "really",
  "some",
  "than",
  "that",
  "their",
  "there",
  "these",
  "they",
  "this",
  "through",
  "very",
  "what",
  "when",
  "where",
  "which",
  "with",
  "would",
  "your",
]);

function cleanTranscript(value: string) {
  return value
    .replace(/\[(?:\d{1,2}:)?\d{1,2}:\d{2}(?:\.\d+)?\]/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function words(value: string) {
  return value
    .toLowerCase()
    .replace(/[^\p{L}\p{N}'\s-]/gu, " ")
    .split(/\s+/)
    .filter(Boolean);
}

function phraseScore(value: string) {
  const phraseWords = words(value);
  const distinctiveWords = phraseWords.filter(
    (word) => word.length >= 5 && !STOP_WORDS.has(word),
  );
  const uniqueWords = new Set(distinctiveWords);
  return (
    uniqueWords.size * 5 +
    distinctiveWords.reduce((sum, word) => sum + Math.min(word.length, 12), 0) +
    (/\d/.test(value) ? 8 : 0)
  );
}

function sentenceCandidates(text: string) {
  const sentences = text
    .split(/(?<=[.!?])\s+|\n+/)
    .map((sentence) => sentence.trim().replace(/^[-–—]\s*/, ""))
    .filter(Boolean);
  const candidates = sentences.filter((sentence) => {
    const count = words(sentence).length;
    return count >= 6 && count <= 18 && sentence.length >= 32;
  });
  if (candidates.length) return candidates;

  const transcriptWords = text.split(/\s+/).filter(Boolean);
  const windows: string[] = [];
  for (let index = 0; index + 8 < transcriptWords.length; index += 7) {
    windows.push(transcriptWords.slice(index, index + 11).join(" "));
  }
  return windows;
}

export function transcriptFields(
  value: string,
  provider: "manual" | "faster-whisper",
  language: string | null = null,
) {
  const transcript = cleanTranscript(value).slice(0, 20_000);
  const ranked = sentenceCandidates(transcript)
    .map((phrase) => ({ phrase, score: phraseScore(phrase) }))
    .filter(({ score }) => score >= 24)
    .sort((left, right) => right.score - left.score);

  const discoveryPhrases: string[] = [];
  for (const candidate of ranked) {
    const normalized = candidate.phrase.toLowerCase();
    const overlaps = discoveryPhrases.some((existing) => {
      const existingWords = new Set(words(existing));
      const candidateWords = words(normalized);
      const shared = candidateWords.filter((word) => existingWords.has(word));
      return shared.length / Math.max(candidateWords.length, 1) > 0.62;
    });
    if (!overlaps) discoveryPhrases.push(candidate.phrase.slice(0, 180));
    if (discoveryPhrases.length === 4) break;
  }

  return {
    transcriptStatus: provider === "manual" ? ("provided" as const) : ("ready" as const),
    transcriptLanguage: language,
    transcriptExcerpt: transcript.slice(0, 640) || null,
    discoveryPhrases,
    transcriptProvider: provider,
    transcriptMessage:
      provider === "manual"
        ? "Transcript supplied by the rights holder."
        : "Transcript generated by the local Faster-Whisper worker.",
  };
}

export function emptyTranscriptFields() {
  return {
    transcriptStatus: "not_requested" as const,
    transcriptLanguage: null,
    transcriptExcerpt: null,
    discoveryPhrases: [] as string[],
    transcriptProvider: null,
    transcriptMessage: "No transcript has been supplied or generated.",
  };
}

export function discoverySeeds(title: string, phrases: string[]) {
  const seeds = [...phrases.slice(0, 3), title]
    .map((value) => value.trim())
    .filter(Boolean);
  return [...new Set(seeds)].slice(0, 4);
}

export function textSimilarity(seeds: string[], candidate: string) {
  const normalizedCandidate = cleanTranscript(candidate).toLowerCase();
  let best = 0;

  for (const seed of seeds) {
    const normalizedSeed = cleanTranscript(seed).toLowerCase();
    if (normalizedSeed.length >= 20 && normalizedCandidate.includes(normalizedSeed)) {
      best = Math.max(best, 98);
      continue;
    }

    const seedTerms = new Set(
      words(normalizedSeed).filter((word) => word.length > 2),
    );
    const candidateTerms = new Set(
      words(normalizedCandidate).filter((word) => word.length > 2),
    );
    if (!seedTerms.size || !candidateTerms.size) continue;
    let overlap = 0;
    for (const term of seedTerms) {
      if (candidateTerms.has(term)) overlap += 1;
    }
    const recall = overlap / seedTerms.size;
    const precision = overlap / candidateTerms.size;
    const score =
      recall + precision > 0
        ? Math.round((2 * recall * precision * 100) / (recall + precision))
        : 0;
    best = Math.max(best, score);
  }

  return Math.max(20, Math.min(98, best || 20));
}
